### ISSUE TITLE
Remove mention of topical channels from "#-how-to-get-help" text

### ISSUE THREAD

**Issue by cspotcode** [typescript-community/community-bot#107]
Remove any mention of the topical help channels from the text in #how-to-get-help.  If this change is implemented, it will make the description less confusing because it starts with simple, prescriptive instructions to post in an available #help- channel.

Here are a few messages copied from the relevant Discord discussion:

> cspotcode: The phrasing in #❓-how-to-get-help is, I think, making people feel like the system is more complicated than it really is.  Because instead of saying "post your question in xyz," it opens with "does it fit into this list of channels that you didn't know exist?"

> cspotcode: if someone asks a react question, we can be friendly and say "we talk about this stuff a lot in #react, feel free to join us over there"

> Graff6: This a million times. On the occasion that one of the topical help channels is more appropriate, it's so much less annoying to direct someone from a tree channel to a topical channel

Relevant discussion and rationale here:
https://discord.com/channels/508357248330760243/635484648318697492/808399962320666634

orta suggested I capture the suggestions as GH issues:
https://discord.com/channels/508357248330760243/635484648318697492/809073483468242954

**Comment by tjjfvi** [comment]
Fixed by #135
