### ISSUE TITLE
Shorten "#how-to-get-help" text to the bare minimum

### ISSUE THREAD

**Issue by cspotcode** [typescript-community/community-bot#108]
Walls of text often cause the reader to skip reading the entire thing.  We can shorten the text in #how-to-get-help.  Some of it is not relevant nor useful to someone who wants to ask a question for the first time.  For example, explaining the "Dormant" category is not necessary.

#how-to-get-help's purpose appears to be explaining the system enough for a *first-time* asker, not to explain every detail of the system in detail.  With that goal in mind, the text can be shortened.

**Comment by tjjfvi** [comment]
Likely fixed by #135
