### ISSUE TITLE
Move "Occupied Help Channels" group vertically upward to sit directly beneath "Available Help Channels"

### ISSUE THREAD

**Issue by cspotcode** [typescript-community/community-bot#109]
The goal is to reduce confusion.  By making all help channels adjacent to each other, the "top" help channel is effectively one of the available ones.  As it is today, the "top" channel visually is often the first one within the "Occupied" group, because the "Available" channels are either off-screen or otherwise seem like they are somehow fundamentally different or part of a separate system, due to the confusing sorting of groups.

> Graff6: Seriously though, *most people come to the server to ask a question.* The channel arrangement should reflect that. It's fine for #ts-discussion to be lower down and "buried" because that's a good way to get a better signal-to-noise ratio.

A mockup of how this might look.  Note that the mockup *also* includes an *unrelated* change to the text within #how-to-get-help.  This unrelated change is actually tracked by *other* Github issues; this github issue is *not* proposing changes to the text of #how-to-get-help.

![https://cdn.discordapp.com/attachments/635484648318697492/808405592338726922/unknown.png](https://cdn.discordapp.com/attachments/635484648318697492/808405592338726922/unknown.png)

orta suggested I capture suggestions as GH issues:
https://discord.com/channels/508357248330760243/635484648318697492/809073483468242954

**Comment by mkantor** [comment]
For clarity I made simpler a mockup:

Before:
![Screen Shot 2021-03-01 at 1 32 04 PM](https://user-images.githubusercontent.com/35091/109562610-77958180-7a93-11eb-9fc0-02f41dada9b3.png)

After:
![Screen Shot 2021-03-01 at 1 37 17 PM](https://user-images.githubusercontent.com/35091/109562617-782e1800-7a93-11eb-971b-1f3975145ccd.png)

**Comment by cspotcode** [comment]
I believe this ticket can be closed since it has been implemented and, as far as I know, the change is going to be kept.  I think regulars appreciate how it moves the "General" and "Engineering" categories closer together.

**Comment by robertt** [comment]
Yeah, we're going to keep it, I'll close this.
