### ISSUE TITLE
Rename "cooldown" channel, since the word "cooldown" is a confusing misnomer

### ISSUE THREAD

**Issue by cspotcode** [typescript-community/community-bot#110]
https://discord.com/channels/508357248330760243/508357683506708514/809951073933852752

> Graff6: Rename the "Cooldown" role to "Has help channel". It is easier to explain "You can only have one help channel at once" than "Cooldown means you have an active help channel and cannot open another." In other words, cooldown is an unnecessary abstraction.

https://discord.com/channels/508357248330760243/635484648318697492/809948246477766666

> Graff6: The word "cooldown" seems to confuse people — they often don't realize that it means "has active help channel" and not something more severe.

https://discord.com/channels/508357248330760243/635484648318697492/798274257598808144

> cspotcode: The channel name "cooldown" is a bit of a misnomer, since it's not a timer, rather a limit of 1 help channel at a time.  As far as I know, it's possible to open and close help channels as fast as possible, as long as you only have 1 at a time

**Comment by mkantor** [comment]
Is this no longer relevant with the thread-based help system? I don't think there's a cooldown channel anymore.

**Comment by cspotcode** [comment]
Yeah, I think we can close this.
