### ISSUE TITLE
Add a #help-general as a general help channel, unaffected by the bot's help system

### ISSUE THREAD

**Issue by cspotcode** [typescript-community/community-bot#118]
Create a new channel, `#help-general`, where anyone can ask any help questions, and the bot does not affect it in any way.  It does not follow a "available" / "occupied" / "dormant" lifecycle.  It does not require any code changes in the bot.

Implementation: an administrator create the channel and positions it in the sidebar.

Usage: anyone is free to ask any questions in #help-general.  People who want to avoid claiming a help channel for any reason can ask in #help-general.  Conversations will naturally overlap in this channel.

The existence of this channel does not affect the existing help channel system.

**Comment by fatcerberus** [comment]
This probably isn't relevant now that we've switched to threads
