### ISSUE TITLE
Twoslash replaces `<` with `&lt;` in output

### ISSUE THREAD

**Issue by oliversalzburg** [typescript-community/community-bot#146]
Given a code snippet that contains a `<`, the twoslash command will print `&lt;` in its place.

I believe this is caused by https://github.com/microsoft/TypeScript-Website/blob/v2/packages/ts-twoslasher/src/utils.ts#L1-L3 ultimately.

An example of this behavior can be seen at https://discord.com/channels/508357248330760243/762764001204502649/836933087463866368

**Comment by tjjfvi** [comment]
Unfortunately it doesn't properly escape things like `&lt;`, so an html decode won't be lossless
