### ISSUE TITLE
Add WIKI-section.

### ISSUE THREAD

**Issue by Vadelius** [typescript-community/community-bot#16]
# Expected Behavior

Wiki with Content.

# Current Behavior

No entries.

# Failure Information (for bugs)
## Steps to Reproduce

Goto https://github.com/typescript-community/community-bot/wiki

**Comment by jellz** [comment]
What kind of content do we want to be displayed on the wiki?

**Comment by jellz** [comment]
Also, how are we supposed to contribute to the wiki? The owners of the repo set the wiki to only be editable by people with admin permission, and you can't PR wiki pages AFAIK.

**Comment by orta** [comment]
Yeah, you should probably prefer a docs folder in the repo IMO
