### ISSUE TITLE
`!rep` should work with user IDs

### ISSUE THREAD

**Issue by Josh-Cena** [typescript-community/community-bot#207]
From Chen Sida:

`!rep` should work with user IDs like `!rep 198637352489320450`. Currently it relies on finding the ping in the message instead of the command argument.

**Comment by Retsam** [comment]
I guess I got the tagging syntax wrong, since this didn't close automatically.  (Maybe you can't edit it in?)  @Josh-Cena / @robertt mind closing it?

**Comment by Josh-Cena** [comment]
Yeah, you need one of "fixes", "resolves", or "closes". Anyway, it does seem to work. Thanks!

**Comment by Retsam** [comment]
Ah, I thought "implements" was one of the magic words.  Thanks!
