### ISSUE TITLE
BUG: Pascalify command does not work if text is already in Pascal/camelCase

### ISSUE THREAD

**Issue by Nekoniri** [typescript-community/community-bot#47]
# Expected Behavior
As a user I expect that when I use the `t!pascalify` command that it should convert the given text to PascalCase correctly.
**example**
```
User: t!pascalify thisIs my message
Bot: ThisIsMyMessage
```

# Current Behavior
The command currently converts text that is already in PascalCase or camelCase incorrectly.
**example**
```
User: t!pascalify thisIs my message
Bot: ThisisMyMessage
```

# Failure Information (for bugs)

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Join the Discord server
2. Type `t!pascalify thisIs my message` in the chat
3. Bot will incorrectly respond with `ThisisMyMessage` (note the lowercase `i` in `is`)

## Failure Logs

No logs available.

**Comment by Nekoniri** [comment]
I can't assign it to myself, but I will submit the PR in a bit

**Comment by Haxified** [comment]
👍
