### ISSUE TITLE
Bug: Playground link shortening doesn't work with url params

### ISSUE THREAD

**Issue by Gerrit0** [typescript-community/community-bot#65]
The playground detection checks for the page url, but expects no url parameters, so if you changed the version, it doesn't work. Example - https://www.typescriptlang.org/play?ts=4.0.0-beta#code/

This goes hand in hand with doing this to any url on TS domains with #code, the current setup also wont catch links for the bug workbench.

**Comment by ronthecookie** [comment]
Oh, missed the part about the bug workbench, I'll get to that now.
