### ISSUE TITLE
"Thanks" rep tagging should allow for more then one person to be repped per message

### ISSUE THREAD

**Issue by robertt** [typescript-community/community-bot#80]
Currently, if you say "Thanks @userone @usertwo", only @userone will be repped. There are two solutions I can think of for this:
1. Remove the regex and check if the message contains "Thanks", then just go through the mentions in the message and rep each person.
2. Improve the regex to match multiple people

**Comment by HughMacdonald** [comment]
Is it worth also supporting things like "Thanks! @user", "@user thanks" and "thx @user", all of which I've seen

**Comment by robertt** [comment]
@HughMacdonald Definitely! There's a lot you could do. Another thing I was thinking of, if a message contains "Thanks" with no mentions, would it be worth looking at the previous message that isn't by the same user and giving the author of that message rep?
