### ISSUE TITLE
Emojis for top 3 in leaderboard

### ISSUE THREAD

**Issue by robertt** [typescript-community/community-bot#84]
Currently, the leaderboard looks something like this: 
![image](https://user-images.githubusercontent.com/18425863/94923546-eefac100-04b3-11eb-8037-68b3b27e34cd.png)

It would be cool if we used 🏅 🥈 🥉 emojis for the top 3 instead of ▫️.

**Comment by shngt** [comment]
Hi, I'm interested in picking this up. Any pointers on getting started?

**Comment by robertt** [comment]
Yup! The code with the emojis is right here: https://github.com/typescript-community/community-bot/blob/master/src/modules/rep.ts#L138

You might want to abstract it into a `getLeaderboardEmoji` function which takes in the index and returns the emoji.

**Comment by shngt** [comment]
Thanks! I'll get started right away

**Comment by shngt** [comment]
I think I'm done, but I can't figure out how to test it? Sorry if it's a dumb question, this is my first time working with something like this

**Comment by shngt** [comment]
I think I'm done, but can't seem to figure out how to test it. Sorry if this is super basic, it's my first time working with something like this :\

**Comment by robertt** [comment]
@shngt you'll need to make a bot on the discord developer dashboard, invite it to a testing server and fill out the env file. 

If you want, just submit a pr and I'll test it - I already have a testing env setup.

**Comment by shngt** [comment]
Oh cool thanks, will do then. Might try to set it up for my own benefit
